# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!
  SERVICE_NAME: anonimus-animals

tasks:
  docker-build:
    cmds:
      - docker build -t registry.gitflic.ru/project/kovardin/{{ .SERVICE_NAME }}/{{ .SERVICE_NAME }}:latest -f Dockerfile .

  docker-publish:
    cmds:
      - docker push registry.gitflic.ru/project/kovardin/{{ .SERVICE_NAME }}/{{ .SERVICE_NAME }}:latest

  docker-run:
    cmds:
      - docker run -d -v /Users/artem/projects/anonimus-animals/data:/app/data -p 8888:8000 registry.gitflic.ru/project/kovardin/{{ .SERVICE_NAME }}/{{ .SERVICE_NAME }}:latest

  git-push:
    cmds:
      - git push origin master
      - git push gitflic master
