### list
# GET http://127.0.0.1:8000/animals
GET https://animals.kodikapusta.ru/animals

### add
# POST http://127.0.0.1:8000/animals
POST https://animals.kodikapusta.ru/animals
Content-Type: application/json

### update

PUT https://animals.kodikapusta.ru/animals
Content-Type: application/json

{
    "id":65
}